package fil.tiir.fakedistrib.util;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpDelete;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.BasicResponseHandler;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.util.EntityUtils;
import org.json.JSONException;
import org.json.JSONObject;

import fil.tiir.fakedistrib.entity.Banque;

public class RequestUtil {
	/**
	 * Send a request at the bank without a token
	 * @param toSend
	 * @param banque
	 * @param url
	 * @return
	 * @throws IOException
	 * @throws JSONException 
	 */
	public static String sendRequest(JSONObject toSend, Banque banque, String url) throws IOException, JSONException {
		return sendRequest(toSend, banque, url, null);
	}
	/**
	 * Send a request at the bank with the token token
	 * @param toSend The data to Send at the bank
	 * @param banque the bank to Send the data
	 * @param url the link of the service to join
	 * @param token the token generated by the bank if this is a solde display, a virement or a retrait
	 * @return
	 * @throws IOException
	 * @throws JSONException 
	 */
	public static String sendRequest(JSONObject toSend, Banque banque, String url, String token) throws IOException, JSONException {
		CloseableHttpClient httpClient = HttpClientBuilder.create().build();
		HttpPost request = new HttpPost("http://" + banque.getUrl() + url);
		//StringEntity params = new StringEntity(toSend.toString());
		request.addHeader("content-type", "application/json");
		List<NameValuePair> params2 = new ArrayList<>();
	
		//TODO : Changer car dégeulasse
		String my = toSend.toString();
		String test2 = my.replace("[", ""); 
		test2 = test2.replace("]", "");
		StringEntity params = new StringEntity(test2);

		
		if (token != null)
			request.addHeader("Token", token);
		request.setEntity(params);
		HttpResponse response = httpClient.execute(request);
		ResponseHandler<String> handler = new BasicResponseHandler();
		String body = handler.handleResponse(response);
		httpClient.close();
		//HttpEntity entity = response.getEntity();
		//String responseString = EntityUtils.toString(entity, "UTF-8");
		return body;
	}
	/**
	 * Send a delete request at the banque banque at the url given
	 * @param banque
	 * @param url
	 * @return
	 * @throws IOException
	 */
	public static String sendDeleteRequest(Banque banque, String url) throws IOException{
		CloseableHttpClient httpClient = HttpClientBuilder.create().build();
		HttpDelete request = new HttpDelete("http://" + banque.getUrl() + "/" + url);
		HttpResponse response = httpClient.execute(request);
		httpClient.close();
		HttpEntity entity = response.getEntity();
		String responseString = EntityUtils.toString(entity, "UTF-8");
		return responseString;
	}
	/**
	 * Send a post request at the bank without data to send at the bank
	 * @param banque
	 * @param url
	 * @return
	 * @throws IOException
	 */
	public static String sendBasicPostRequest(Banque banque, String url) throws IOException {
		
		CloseableHttpClient httpClient = HttpClientBuilder.create().build();
		HttpPost request = new HttpPost("http://" + banque.getUrl() + "/" + url);
		HttpResponse response = httpClient.execute(request);
		httpClient.close();
		HttpEntity entity = response.getEntity();
		String responseString = EntityUtils.toString(entity, "UTF-8");
		return responseString;
	}
}
